// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwXGHNg6eV-ABZKvK1SWGpUxb7Fh-8RRI',
    appId: '1:1046085330534:web:39e08c1f748fe93b4bafa7',
    messagingSenderId: '1046085330534',
    projectId: 'pulseflow-f9154',
    authDomain: 'pulseflow-f9154.firebaseapp.com',
    storageBucket: 'pulseflow-f9154.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6KsBiLks3LBrbiI2Dy5IO5VN7IxRcsE4',
    appId: '1:1046085330534:android:4736c817cc5724d74bafa7',
    messagingSenderId: '1046085330534',
    projectId: 'pulseflow-f9154',
    storageBucket: 'pulseflow-f9154.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLZjlo5cTcszypq-DI0ppIO74TNiFgdY',
    appId: '1:1046085330534:ios:58fd0f5f398ea5264bafa7',
    messagingSenderId: '1046085330534',
    projectId: 'pulseflow-f9154',
    storageBucket: 'pulseflow-f9154.firebasestorage.app',
    iosBundleId: 'com.example.pacienteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy-macOSKey-ForPulseFlow',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'pulseflow-app',
    storageBucket: 'pulseflow-app.appspot.com',
    iosBundleId: 'com.example.pacienteApp',
  );
}
